### ISSUE TITLE
Consider supporting repository files instead of gists

### ISSUE THREAD

**Issue by luxaritas** [cla-assistant/cla-assistant#926]
Basically, my goal would be to create a CLA.md file in our organization GitHub repository, that way it could be easily updated by anyone in our organization, vs having to rely on the gist being tied to personal accounts

**Comment by ReenigneArcher** [comment]
As a workaround, you can replicate files from a repo to a gist. This is how I handle it for my org.

```yml
---
name: CLA gist replicator

on:
  push:
    branches: [master]
    paths:
      - "cla/**"
  workflow_dispatch:

jobs:
  replicate_cla:
    name: Replicate CLA
    runs-on: ubuntu-latest

    strategy:  # the action doesn't currently support multiple files
      fail-fast: true  # false to run all, true to fail entire job if any fail
      max-parallel: 1  # let's update files one by one to avoid complications
      matrix:
        include:
          - file_path: 'cla/CLA'
          - file_path: 'cla/CLA-entity'
          - file_path: 'cla/metadata'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          gist_id: ${{ secrets.CLA_GIST_ID }}
          file_path: ${{ matrix.file_path }}
          file_type: text
```
